name: Pull Request
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions:
    name: Lint GitHub Actions Workflows
    uses: ./.github/workflows/lint-actions.yml

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml